spring:
  profiles:
#    active: db, core, admin, wx
    active: db, core, admin
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 9000
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

logging:
  config: classpath:logback-spring.xml

swagger:
  production: false