package com.beauty.mhzc.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class Applet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.applet_id
     *
     * @mbg.generated
     */
    private String appletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.applet_secret
     *
     * @mbg.generated
     */
    private String appletSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.wechat_pay_merchant
     *
     * @mbg.generated
     */
    private String wechatPayMerchant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.wechat_pay_api_key
     *
     * @mbg.generated
     */
    private String wechatPayApiKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.api_client_cert
     *
     * @mbg.generated
     */
    private String apiClientCert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.api_client_key
     *
     * @mbg.generated
     */
    private String apiClientKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.mall_id
     *
     * @mbg.generated
     */
    private String mallId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.id
     *
     * @return the value of applet.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.id
     *
     * @param id the value for applet.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.applet_id
     *
     * @return the value of applet.applet_id
     *
     * @mbg.generated
     */
    public String getAppletId() {
        return appletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.applet_id
     *
     * @param appletId the value for applet.applet_id
     *
     * @mbg.generated
     */
    public void setAppletId(String appletId) {
        this.appletId = appletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.applet_secret
     *
     * @return the value of applet.applet_secret
     *
     * @mbg.generated
     */
    public String getAppletSecret() {
        return appletSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.applet_secret
     *
     * @param appletSecret the value for applet.applet_secret
     *
     * @mbg.generated
     */
    public void setAppletSecret(String appletSecret) {
        this.appletSecret = appletSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.wechat_pay_merchant
     *
     * @return the value of applet.wechat_pay_merchant
     *
     * @mbg.generated
     */
    public String getWechatPayMerchant() {
        return wechatPayMerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.wechat_pay_merchant
     *
     * @param wechatPayMerchant the value for applet.wechat_pay_merchant
     *
     * @mbg.generated
     */
    public void setWechatPayMerchant(String wechatPayMerchant) {
        this.wechatPayMerchant = wechatPayMerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.wechat_pay_api_key
     *
     * @return the value of applet.wechat_pay_api_key
     *
     * @mbg.generated
     */
    public String getWechatPayApiKey() {
        return wechatPayApiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.wechat_pay_api_key
     *
     * @param wechatPayApiKey the value for applet.wechat_pay_api_key
     *
     * @mbg.generated
     */
    public void setWechatPayApiKey(String wechatPayApiKey) {
        this.wechatPayApiKey = wechatPayApiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.api_client_cert
     *
     * @return the value of applet.api_client_cert
     *
     * @mbg.generated
     */
    public String getApiClientCert() {
        return apiClientCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.api_client_cert
     *
     * @param apiClientCert the value for applet.api_client_cert
     *
     * @mbg.generated
     */
    public void setApiClientCert(String apiClientCert) {
        this.apiClientCert = apiClientCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.api_client_key
     *
     * @return the value of applet.api_client_key
     *
     * @mbg.generated
     */
    public String getApiClientKey() {
        return apiClientKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.api_client_key
     *
     * @param apiClientKey the value for applet.api_client_key
     *
     * @mbg.generated
     */
    public void setApiClientKey(String apiClientKey) {
        this.apiClientKey = apiClientKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.mall_id
     *
     * @return the value of applet.mall_id
     *
     * @mbg.generated
     */
    public String getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.mall_id
     *
     * @param mallId the value for applet.mall_id
     *
     * @mbg.generated
     */
    public void setMallId(String mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appletId=").append(appletId);
        sb.append(", appletSecret=").append(appletSecret);
        sb.append(", wechatPayMerchant=").append(wechatPayMerchant);
        sb.append(", wechatPayApiKey=").append(wechatPayApiKey);
        sb.append(", apiClientCert=").append(apiClientCert);
        sb.append(", apiClientKey=").append(apiClientKey);
        sb.append(", mallId=").append(mallId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Applet other = (Applet) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppletId() == null ? other.getAppletId() == null : this.getAppletId().equals(other.getAppletId()))
            && (this.getAppletSecret() == null ? other.getAppletSecret() == null : this.getAppletSecret().equals(other.getAppletSecret()))
            && (this.getWechatPayMerchant() == null ? other.getWechatPayMerchant() == null : this.getWechatPayMerchant().equals(other.getWechatPayMerchant()))
            && (this.getWechatPayApiKey() == null ? other.getWechatPayApiKey() == null : this.getWechatPayApiKey().equals(other.getWechatPayApiKey()))
            && (this.getApiClientCert() == null ? other.getApiClientCert() == null : this.getApiClientCert().equals(other.getApiClientCert()))
            && (this.getApiClientKey() == null ? other.getApiClientKey() == null : this.getApiClientKey().equals(other.getApiClientKey()))
            && (this.getMallId() == null ? other.getMallId() == null : this.getMallId().equals(other.getMallId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppletId() == null) ? 0 : getAppletId().hashCode());
        result = prime * result + ((getAppletSecret() == null) ? 0 : getAppletSecret().hashCode());
        result = prime * result + ((getWechatPayMerchant() == null) ? 0 : getWechatPayMerchant().hashCode());
        result = prime * result + ((getWechatPayApiKey() == null) ? 0 : getWechatPayApiKey().hashCode());
        result = prime * result + ((getApiClientCert() == null) ? 0 : getApiClientCert().hashCode());
        result = prime * result + ((getApiClientKey() == null) ? 0 : getApiClientKey().hashCode());
        result = prime * result + ((getMallId() == null) ? 0 : getMallId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table applet
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        appletId("applet_id", "appletId", "VARCHAR", false),
        appletSecret("applet_secret", "appletSecret", "VARCHAR", false),
        wechatPayMerchant("wechat_pay_merchant", "wechatPayMerchant", "VARCHAR", false),
        wechatPayApiKey("wechat_pay_api_key", "wechatPayApiKey", "VARCHAR", false),
        apiClientCert("api_client_cert", "apiClientCert", "VARCHAR", false),
        apiClientKey("api_client_key", "apiClientKey", "VARCHAR", false),
        mallId("mall_id", "mallId", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}