package com.beauty.mhzc.db.domain;

import java.util.ArrayList;
import java.util.List;

public class AppletExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applet
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applet
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applet
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public AppletExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public AppletExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public AppletExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AppletExample example = new AppletExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public AppletExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public AppletExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applet
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppletIdIsNull() {
            addCriterion("applet_id is null");
            return (Criteria) this;
        }

        public Criteria andAppletIdIsNotNull() {
            addCriterion("applet_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppletIdEqualTo(String value) {
            addCriterion("applet_id =", value, "appletId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletIdEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletIdNotEqualTo(String value) {
            addCriterion("applet_id <>", value, "appletId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletIdNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletIdGreaterThan(String value) {
            addCriterion("applet_id >", value, "appletId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletIdGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletIdGreaterThanOrEqualTo(String value) {
            addCriterion("applet_id >=", value, "appletId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletIdGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletIdLessThan(String value) {
            addCriterion("applet_id <", value, "appletId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletIdLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletIdLessThanOrEqualTo(String value) {
            addCriterion("applet_id <=", value, "appletId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletIdLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletIdLike(String value) {
            addCriterion("applet_id like", value, "appletId");
            return (Criteria) this;
        }

        public Criteria andAppletIdNotLike(String value) {
            addCriterion("applet_id not like", value, "appletId");
            return (Criteria) this;
        }

        public Criteria andAppletIdIn(List<String> values) {
            addCriterion("applet_id in", values, "appletId");
            return (Criteria) this;
        }

        public Criteria andAppletIdNotIn(List<String> values) {
            addCriterion("applet_id not in", values, "appletId");
            return (Criteria) this;
        }

        public Criteria andAppletIdBetween(String value1, String value2) {
            addCriterion("applet_id between", value1, value2, "appletId");
            return (Criteria) this;
        }

        public Criteria andAppletIdNotBetween(String value1, String value2) {
            addCriterion("applet_id not between", value1, value2, "appletId");
            return (Criteria) this;
        }

        public Criteria andAppletSecretIsNull() {
            addCriterion("applet_secret is null");
            return (Criteria) this;
        }

        public Criteria andAppletSecretIsNotNull() {
            addCriterion("applet_secret is not null");
            return (Criteria) this;
        }

        public Criteria andAppletSecretEqualTo(String value) {
            addCriterion("applet_secret =", value, "appletSecret");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletSecretEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_secret = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletSecretNotEqualTo(String value) {
            addCriterion("applet_secret <>", value, "appletSecret");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletSecretNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_secret <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletSecretGreaterThan(String value) {
            addCriterion("applet_secret >", value, "appletSecret");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletSecretGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_secret > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletSecretGreaterThanOrEqualTo(String value) {
            addCriterion("applet_secret >=", value, "appletSecret");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletSecretGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_secret >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletSecretLessThan(String value) {
            addCriterion("applet_secret <", value, "appletSecret");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletSecretLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_secret < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletSecretLessThanOrEqualTo(String value) {
            addCriterion("applet_secret <=", value, "appletSecret");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andAppletSecretLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("applet_secret <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAppletSecretLike(String value) {
            addCriterion("applet_secret like", value, "appletSecret");
            return (Criteria) this;
        }

        public Criteria andAppletSecretNotLike(String value) {
            addCriterion("applet_secret not like", value, "appletSecret");
            return (Criteria) this;
        }

        public Criteria andAppletSecretIn(List<String> values) {
            addCriterion("applet_secret in", values, "appletSecret");
            return (Criteria) this;
        }

        public Criteria andAppletSecretNotIn(List<String> values) {
            addCriterion("applet_secret not in", values, "appletSecret");
            return (Criteria) this;
        }

        public Criteria andAppletSecretBetween(String value1, String value2) {
            addCriterion("applet_secret between", value1, value2, "appletSecret");
            return (Criteria) this;
        }

        public Criteria andAppletSecretNotBetween(String value1, String value2) {
            addCriterion("applet_secret not between", value1, value2, "appletSecret");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantIsNull() {
            addCriterion("wechat_pay_merchant is null");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantIsNotNull() {
            addCriterion("wechat_pay_merchant is not null");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantEqualTo(String value) {
            addCriterion("wechat_pay_merchant =", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayMerchantEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_merchant = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantNotEqualTo(String value) {
            addCriterion("wechat_pay_merchant <>", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayMerchantNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_merchant <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantGreaterThan(String value) {
            addCriterion("wechat_pay_merchant >", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayMerchantGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_merchant > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_pay_merchant >=", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayMerchantGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_merchant >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantLessThan(String value) {
            addCriterion("wechat_pay_merchant <", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayMerchantLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_merchant < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantLessThanOrEqualTo(String value) {
            addCriterion("wechat_pay_merchant <=", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayMerchantLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_merchant <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantLike(String value) {
            addCriterion("wechat_pay_merchant like", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantNotLike(String value) {
            addCriterion("wechat_pay_merchant not like", value, "wechatPayMerchant");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantIn(List<String> values) {
            addCriterion("wechat_pay_merchant in", values, "wechatPayMerchant");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantNotIn(List<String> values) {
            addCriterion("wechat_pay_merchant not in", values, "wechatPayMerchant");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantBetween(String value1, String value2) {
            addCriterion("wechat_pay_merchant between", value1, value2, "wechatPayMerchant");
            return (Criteria) this;
        }

        public Criteria andWechatPayMerchantNotBetween(String value1, String value2) {
            addCriterion("wechat_pay_merchant not between", value1, value2, "wechatPayMerchant");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyIsNull() {
            addCriterion("wechat_pay_api_key is null");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyIsNotNull() {
            addCriterion("wechat_pay_api_key is not null");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyEqualTo(String value) {
            addCriterion("wechat_pay_api_key =", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayApiKeyEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_api_key = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyNotEqualTo(String value) {
            addCriterion("wechat_pay_api_key <>", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayApiKeyNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_api_key <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyGreaterThan(String value) {
            addCriterion("wechat_pay_api_key >", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayApiKeyGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_api_key > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_pay_api_key >=", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayApiKeyGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_api_key >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyLessThan(String value) {
            addCriterion("wechat_pay_api_key <", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayApiKeyLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_api_key < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyLessThanOrEqualTo(String value) {
            addCriterion("wechat_pay_api_key <=", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andWechatPayApiKeyLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("wechat_pay_api_key <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyLike(String value) {
            addCriterion("wechat_pay_api_key like", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyNotLike(String value) {
            addCriterion("wechat_pay_api_key not like", value, "wechatPayApiKey");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyIn(List<String> values) {
            addCriterion("wechat_pay_api_key in", values, "wechatPayApiKey");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyNotIn(List<String> values) {
            addCriterion("wechat_pay_api_key not in", values, "wechatPayApiKey");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyBetween(String value1, String value2) {
            addCriterion("wechat_pay_api_key between", value1, value2, "wechatPayApiKey");
            return (Criteria) this;
        }

        public Criteria andWechatPayApiKeyNotBetween(String value1, String value2) {
            addCriterion("wechat_pay_api_key not between", value1, value2, "wechatPayApiKey");
            return (Criteria) this;
        }

        public Criteria andApiClientCertIsNull() {
            addCriterion("api_client_cert is null");
            return (Criteria) this;
        }

        public Criteria andApiClientCertIsNotNull() {
            addCriterion("api_client_cert is not null");
            return (Criteria) this;
        }

        public Criteria andApiClientCertEqualTo(String value) {
            addCriterion("api_client_cert =", value, "apiClientCert");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientCertEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_cert = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientCertNotEqualTo(String value) {
            addCriterion("api_client_cert <>", value, "apiClientCert");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientCertNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_cert <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientCertGreaterThan(String value) {
            addCriterion("api_client_cert >", value, "apiClientCert");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientCertGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_cert > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientCertGreaterThanOrEqualTo(String value) {
            addCriterion("api_client_cert >=", value, "apiClientCert");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientCertGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_cert >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientCertLessThan(String value) {
            addCriterion("api_client_cert <", value, "apiClientCert");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientCertLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_cert < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientCertLessThanOrEqualTo(String value) {
            addCriterion("api_client_cert <=", value, "apiClientCert");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientCertLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_cert <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientCertLike(String value) {
            addCriterion("api_client_cert like", value, "apiClientCert");
            return (Criteria) this;
        }

        public Criteria andApiClientCertNotLike(String value) {
            addCriterion("api_client_cert not like", value, "apiClientCert");
            return (Criteria) this;
        }

        public Criteria andApiClientCertIn(List<String> values) {
            addCriterion("api_client_cert in", values, "apiClientCert");
            return (Criteria) this;
        }

        public Criteria andApiClientCertNotIn(List<String> values) {
            addCriterion("api_client_cert not in", values, "apiClientCert");
            return (Criteria) this;
        }

        public Criteria andApiClientCertBetween(String value1, String value2) {
            addCriterion("api_client_cert between", value1, value2, "apiClientCert");
            return (Criteria) this;
        }

        public Criteria andApiClientCertNotBetween(String value1, String value2) {
            addCriterion("api_client_cert not between", value1, value2, "apiClientCert");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyIsNull() {
            addCriterion("api_client_key is null");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyIsNotNull() {
            addCriterion("api_client_key is not null");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyEqualTo(String value) {
            addCriterion("api_client_key =", value, "apiClientKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientKeyEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_key = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientKeyNotEqualTo(String value) {
            addCriterion("api_client_key <>", value, "apiClientKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientKeyNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_key <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientKeyGreaterThan(String value) {
            addCriterion("api_client_key >", value, "apiClientKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientKeyGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_key > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientKeyGreaterThanOrEqualTo(String value) {
            addCriterion("api_client_key >=", value, "apiClientKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientKeyGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_key >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientKeyLessThan(String value) {
            addCriterion("api_client_key <", value, "apiClientKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientKeyLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_key < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientKeyLessThanOrEqualTo(String value) {
            addCriterion("api_client_key <=", value, "apiClientKey");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andApiClientKeyLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("api_client_key <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andApiClientKeyLike(String value) {
            addCriterion("api_client_key like", value, "apiClientKey");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyNotLike(String value) {
            addCriterion("api_client_key not like", value, "apiClientKey");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyIn(List<String> values) {
            addCriterion("api_client_key in", values, "apiClientKey");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyNotIn(List<String> values) {
            addCriterion("api_client_key not in", values, "apiClientKey");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyBetween(String value1, String value2) {
            addCriterion("api_client_key between", value1, value2, "apiClientKey");
            return (Criteria) this;
        }

        public Criteria andApiClientKeyNotBetween(String value1, String value2) {
            addCriterion("api_client_key not between", value1, value2, "apiClientKey");
            return (Criteria) this;
        }

        public Criteria andMallIdIsNull() {
            addCriterion("mall_id is null");
            return (Criteria) this;
        }

        public Criteria andMallIdIsNotNull() {
            addCriterion("mall_id is not null");
            return (Criteria) this;
        }

        public Criteria andMallIdEqualTo(String value) {
            addCriterion("mall_id =", value, "mallId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andMallIdEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("mall_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMallIdNotEqualTo(String value) {
            addCriterion("mall_id <>", value, "mallId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andMallIdNotEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("mall_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThan(String value) {
            addCriterion("mall_id >", value, "mallId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andMallIdGreaterThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("mall_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMallIdGreaterThanOrEqualTo(String value) {
            addCriterion("mall_id >=", value, "mallId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andMallIdGreaterThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("mall_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMallIdLessThan(String value) {
            addCriterion("mall_id <", value, "mallId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andMallIdLessThanColumn(Applet.Column column) {
            addCriterion(new StringBuilder("mall_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMallIdLessThanOrEqualTo(String value) {
            addCriterion("mall_id <=", value, "mallId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria andMallIdLessThanOrEqualToColumn(Applet.Column column) {
            addCriterion(new StringBuilder("mall_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMallIdLike(String value) {
            addCriterion("mall_id like", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotLike(String value) {
            addCriterion("mall_id not like", value, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdIn(List<String> values) {
            addCriterion("mall_id in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotIn(List<String> values) {
            addCriterion("mall_id not in", values, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdBetween(String value1, String value2) {
            addCriterion("mall_id between", value1, value2, "mallId");
            return (Criteria) this;
        }

        public Criteria andMallIdNotBetween(String value1, String value2) {
            addCriterion("mall_id not between", value1, value2, "mallId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applet
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private AppletExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        protected Criteria(AppletExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public AppletExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table applet
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table applet
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        void example(com.beauty.mhzc.db.domain.AppletExample example);
    }
}