package com.beauty.mhzc.db.domain;

import javax.validation.constraints.NotEmpty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Applet {

    /**
     * 新增的用户组
     */
    public interface InsertGroup {
    }

    public interface UpdateGroup{

    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applet
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table applet
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.id
     *
     * @mbg.generated
     */
    @NotEmpty(message = "小程序id不能为空",groups = {UpdateGroup.class} )
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.applet_id
     *
     * @mbg.generated
     */
    @NotEmpty(message = "小程序AppId不能为空",groups = {InsertGroup.class,UpdateGroup.class} )
    private String appletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.applet_secret
     *
     * @mbg.generated
     */
    private String appletSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.wechat_pay_merchant
     *
     * @mbg.generated
     */
    private String wechatPayMerchant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.wechat_pay_api_key
     *
     * @mbg.generated
     */
    private String wechatPayApiKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.api_client_cert
     *
     * @mbg.generated
     */
    private String apiClientCert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.api_client_key
     *
     * @mbg.generated
     */
    private String apiClientKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.create_on
     *
     * @mbg.generated
     */
    private LocalDateTime createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.update_on
     *
     * @mbg.generated
     */
    private LocalDateTime updateOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applet.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.id
     *
     * @return the value of applet.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.id
     *
     * @param id the value for applet.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.applet_id
     *
     * @return the value of applet.applet_id
     *
     * @mbg.generated
     */
    public String getAppletId() {
        return appletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.applet_id
     *
     * @param appletId the value for applet.applet_id
     *
     * @mbg.generated
     */
    public void setAppletId(String appletId) {
        this.appletId = appletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.applet_secret
     *
     * @return the value of applet.applet_secret
     *
     * @mbg.generated
     */
    public String getAppletSecret() {
        return appletSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.applet_secret
     *
     * @param appletSecret the value for applet.applet_secret
     *
     * @mbg.generated
     */
    public void setAppletSecret(String appletSecret) {
        this.appletSecret = appletSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.wechat_pay_merchant
     *
     * @return the value of applet.wechat_pay_merchant
     *
     * @mbg.generated
     */
    public String getWechatPayMerchant() {
        return wechatPayMerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.wechat_pay_merchant
     *
     * @param wechatPayMerchant the value for applet.wechat_pay_merchant
     *
     * @mbg.generated
     */
    public void setWechatPayMerchant(String wechatPayMerchant) {
        this.wechatPayMerchant = wechatPayMerchant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.wechat_pay_api_key
     *
     * @return the value of applet.wechat_pay_api_key
     *
     * @mbg.generated
     */
    public String getWechatPayApiKey() {
        return wechatPayApiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.wechat_pay_api_key
     *
     * @param wechatPayApiKey the value for applet.wechat_pay_api_key
     *
     * @mbg.generated
     */
    public void setWechatPayApiKey(String wechatPayApiKey) {
        this.wechatPayApiKey = wechatPayApiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.api_client_cert
     *
     * @return the value of applet.api_client_cert
     *
     * @mbg.generated
     */
    public String getApiClientCert() {
        return apiClientCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.api_client_cert
     *
     * @param apiClientCert the value for applet.api_client_cert
     *
     * @mbg.generated
     */
    public void setApiClientCert(String apiClientCert) {
        this.apiClientCert = apiClientCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.api_client_key
     *
     * @return the value of applet.api_client_key
     *
     * @mbg.generated
     */
    public String getApiClientKey() {
        return apiClientKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.api_client_key
     *
     * @param apiClientKey the value for applet.api_client_key
     *
     * @mbg.generated
     */
    public void setApiClientKey(String apiClientKey) {
        this.apiClientKey = apiClientKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.create_on
     *
     * @return the value of applet.create_on
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.create_on
     *
     * @param createOn the value for applet.create_on
     *
     * @mbg.generated
     */
    public void setCreateOn(LocalDateTime createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.create_by
     *
     * @return the value of applet.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.create_by
     *
     * @param createBy the value for applet.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.update_on
     *
     * @return the value of applet.update_on
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.update_on
     *
     * @param updateOn the value for applet.update_on
     *
     * @mbg.generated
     */
    public void setUpdateOn(LocalDateTime updateOn) {
        this.updateOn = updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.update_by
     *
     * @return the value of applet.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.update_by
     *
     * @param updateBy the value for applet.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applet.deleted
     *
     * @return the value of applet.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applet.deleted
     *
     * @param deleted the value for applet.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", appletId=").append(appletId);
        sb.append(", appletSecret=").append(appletSecret);
        sb.append(", wechatPayMerchant=").append(wechatPayMerchant);
        sb.append(", wechatPayApiKey=").append(wechatPayApiKey);
        sb.append(", apiClientCert=").append(apiClientCert);
        sb.append(", apiClientKey=").append(apiClientKey);
        sb.append(", createOn=").append(createOn);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateOn=").append(updateOn);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Applet other = (Applet) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppletId() == null ? other.getAppletId() == null : this.getAppletId().equals(other.getAppletId()))
            && (this.getAppletSecret() == null ? other.getAppletSecret() == null : this.getAppletSecret().equals(other.getAppletSecret()))
            && (this.getWechatPayMerchant() == null ? other.getWechatPayMerchant() == null : this.getWechatPayMerchant().equals(other.getWechatPayMerchant()))
            && (this.getWechatPayApiKey() == null ? other.getWechatPayApiKey() == null : this.getWechatPayApiKey().equals(other.getWechatPayApiKey()))
            && (this.getApiClientCert() == null ? other.getApiClientCert() == null : this.getApiClientCert().equals(other.getApiClientCert()))
            && (this.getApiClientKey() == null ? other.getApiClientKey() == null : this.getApiClientKey().equals(other.getApiClientKey()))
            && (this.getCreateOn() == null ? other.getCreateOn() == null : this.getCreateOn().equals(other.getCreateOn()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getUpdateOn() == null ? other.getUpdateOn() == null : this.getUpdateOn().equals(other.getUpdateOn()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppletId() == null) ? 0 : getAppletId().hashCode());
        result = prime * result + ((getAppletSecret() == null) ? 0 : getAppletSecret().hashCode());
        result = prime * result + ((getWechatPayMerchant() == null) ? 0 : getWechatPayMerchant().hashCode());
        result = prime * result + ((getWechatPayApiKey() == null) ? 0 : getWechatPayApiKey().hashCode());
        result = prime * result + ((getApiClientCert() == null) ? 0 : getApiClientCert().hashCode());
        result = prime * result + ((getApiClientKey() == null) ? 0 : getApiClientKey().hashCode());
        result = prime * result + ((getCreateOn() == null) ? 0 : getCreateOn().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getUpdateOn() == null) ? 0 : getUpdateOn().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table applet
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table applet
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        appletId("applet_id", "appletId", "VARCHAR", false),
        appletSecret("applet_secret", "appletSecret", "VARCHAR", false),
        wechatPayMerchant("wechat_pay_merchant", "wechatPayMerchant", "VARCHAR", false),
        wechatPayApiKey("wechat_pay_api_key", "wechatPayApiKey", "VARCHAR", false),
        apiClientCert("api_client_cert", "apiClientCert", "VARCHAR", false),
        apiClientKey("api_client_key", "apiClientKey", "VARCHAR", false),
        createOn("create_on", "createOn", "TIMESTAMP", false),
        createBy("create_by", "createBy", "VARCHAR", false),
        updateOn("update_on", "updateOn", "TIMESTAMP", false),
        updateBy("update_by", "updateBy", "VARCHAR", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table applet
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table applet
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}