package com.beauty.mhzc.db.dao;

import com.beauty.mhzc.db.domain.Applet;
import com.beauty.mhzc.db.domain.AppletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    long countByExample(AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int deleteByExample(AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int insert(Applet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int insertSelective(Applet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    Applet selectOneByExample(AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    Applet selectOneByExampleSelective(@Param("example") AppletExample example, @Param("selective") Applet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    List<Applet> selectByExampleSelective(@Param("example") AppletExample example, @Param("selective") Applet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    List<Applet> selectByExample(AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    Applet selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") Applet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    Applet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    Applet selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Applet record, @Param("example") AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Applet record, @Param("example") AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Applet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Applet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") AppletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applet
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(String id);
}