package com.beauty.mhzc.db.dao;

import com.beauty.mhzc.db.domain.MallManager;
import com.beauty.mhzc.db.domain.MallManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    long countByExample(MallManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int deleteByExample(MallManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int insert(MallManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int insertSelective(MallManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    MallManager selectOneByExample(MallManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    MallManager selectOneByExampleSelective(@Param("example") MallManagerExample example, @Param("selective") MallManager.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    List<MallManager> selectByExampleSelective(@Param("example") MallManagerExample example, @Param("selective") MallManager.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    List<MallManager> selectByExample(MallManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    MallManager selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") MallManager.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    MallManager selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallManager record, @Param("example") MallManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallManager record, @Param("example") MallManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallManager record);

    /**
     * 批量添加
     * @param list
     */
    void insertBatch(List<MallManager> list);
}