package com.beauty.mhzc.db.dao;

import com.beauty.mhzc.db.domain.Mall;
import com.beauty.mhzc.db.domain.MallExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    long countByExample(MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int deleteByExample(MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int insert(Mall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int insertSelective(Mall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    Mall selectOneByExample(MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    Mall selectOneByExampleSelective(@Param("example") MallExample example, @Param("selective") Mall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    List<Mall> selectByExampleSelective(@Param("example") MallExample example, @Param("selective") Mall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    List<Mall> selectByExample(MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    Mall selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") Mall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    Mall selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    Mall selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Mall record, @Param("example") MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Mall record, @Param("example") MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Mall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Mall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(String id);

    Mall selectByCondition(@Param("mallId") String mallId,@Param("managerId") Integer managerId);
}