spring:
  profiles:
    active: db,wx
  messages:
    encoding: UTF-8

server:
  port: 9001


  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
    database: 0

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root:  INFO
    org.springframework:  INFO
    org.mybatis:  INFO
    com.beauty.mhzc.db.dao: INFO

wx:
  miniapp:
    appid: wx8cfd8b8e050ebf5d
    appsecret: 903ca7f3197b3fae61a1315b7afc0e97
#swagger:
#  production: true