spring:
  profiles:
    active: db,wx
  messages:
    encoding: UTF-8

server:
  port: 9001


  redis:
    host: 127.0.0.1
    password: ''
    port: 6379
    database: 0

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework.web: info
    com.beauty.mhzc: debug
    cn.binarywang.wx.miniapp: debug

wx:
  miniapp:
    configs:
      - appid: wx8cfd8b8e050ebf5d
        secret: 903ca7f3197b3fae61a1315b7afc0e97
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
    enabled: true
  packages-to-scan: com.beauty.mhzc.wx.controller
  paths-to-match: /**
  api-docs:
    path: /doc/api
    enabled: true
#  show-actuator: true
#  use-management-port: true
#management:
#  endpoints:
#    web:
#      exposure:
#        includ: openapi, swaggerui
#  server:
#    port=9090: