spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8080


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root:  INFO
    org.springframework:  INFO
    org.mybatis:  INFO
    com.beauty.mhzc.db.dao: INFO

#swagger:
#  production: true